
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NOMVARIABLE = 32;
  public static final int RINICIO = 27;
  public static final int POR = 14;
  public static final int RFALSO = 42;
  public static final int NUMDATO = 33;
  public static final int RMENORIGUAL = 21;
  public static final int ENTERO = 38;
  public static final int RDIFERENTE = 23;
  public static final int CADDATO = 35;
  public static final int LLAVIZQ = 7;
  public static final int RMOD = 17;
  public static final int RELSE = 48;
  public static final int RMAYORIGUAL = 20;
  public static final int RMIENTRAS = 49;
  public static final int IGUAL = 44;
  public static final int CARACTER = 39;
  public static final int CORDER = 6;
  public static final int RCONVALOR = 31;
  public static final int DIVIDIDO = 15;
  public static final int CARDATO = 37;
  public static final int UMENOS = 45;
  public static final int REVALUAR = 46;
  public static final int BOOLDATO = 36;
  public static final int DECIMAL = 43;
  public static final int EOF = 0;
  public static final int PARIZQ = 3;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int CADENA = 40;
  public static final int MENOS = 13;
  public static final int COMSIMPLE = 10;
  public static final int RPOTENCIA = 16;
  public static final int RIGUAL = 22;
  public static final int FLOATDATO = 34;
  public static final int LLAVDER = 8;
  public static final int RINGRESAR = 29;
  public static final int PTCOMA = 2;
  public static final int ROR = 24;
  public static final int RVERDADERO = 41;
  public static final int RMENOR = 19;
  public static final int PARDER = 4;
  public static final int RFIN = 28;
  public static final int CORIZQ = 5;
  public static final int RIF = 47;
  public static final int DOLAR = 9;
  public static final int RCOMO = 30;
  public static final int RNOT = 26;
  public static final int RAND = 25;
  public static final int RMAYOR = 18;
  public static final int MAS = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "CORIZQ",
  "CORDER",
  "LLAVIZQ",
  "LLAVDER",
  "DOLAR",
  "COMSIMPLE",
  "COMA",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "RPOTENCIA",
  "RMOD",
  "RMAYOR",
  "RMENOR",
  "RMAYORIGUAL",
  "RMENORIGUAL",
  "RIGUAL",
  "RDIFERENTE",
  "ROR",
  "RAND",
  "RNOT",
  "RINICIO",
  "RFIN",
  "RINGRESAR",
  "RCOMO",
  "RCONVALOR",
  "NOMVARIABLE",
  "NUMDATO",
  "FLOATDATO",
  "CADDATO",
  "BOOLDATO",
  "CARDATO",
  "ENTERO",
  "CARACTER",
  "CADENA",
  "RVERDADERO",
  "RFALSO",
  "DECIMAL",
  "IGUAL",
  "UMENOS",
  "REVALUAR",
  "RIF",
  "RELSE",
  "RMIENTRAS"
  };
}

