
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NOMVARIABLE = 33;
  public static final int RINICIO = 28;
  public static final int CHAR = 41;
  public static final int POR = 15;
  public static final int RENTONCES = 53;
  public static final int RFALSO = 44;
  public static final int NUMDATO = 34;
  public static final int RMENORIGUAL = 22;
  public static final int ENTERO = 40;
  public static final int RDIFERENTE = 24;
  public static final int CADDATO = 36;
  public static final int LLAVIZQ = 7;
  public static final int RMOD = 18;
  public static final int RELSE = 55;
  public static final int RMAYORIGUAL = 21;
  public static final int RMIENTRAS = 51;
  public static final int IGUAL = 46;
  public static final int CORDER = 6;
  public static final int RCONVALOR = 32;
  public static final int DIVIDIDO = 16;
  public static final int CARDATO = 38;
  public static final int UMENOS = 47;
  public static final int REVALUAR = 48;
  public static final int BOOLDATO = 37;
  public static final int DECIMAL = 45;
  public static final int EOF = 0;
  public static final int PARIZQ = 3;
  public static final int RFIN_SI = 54;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int FLECHAASIGN = 39;
  public static final int MENOS = 14;
  public static final int COMSIMPLE = 10;
  public static final int RPOTENCIA = 17;
  public static final int RIGUAL = 23;
  public static final int RSI = 52;
  public static final int ROSI = 56;
  public static final int FLOATDATO = 35;
  public static final int LLAVDER = 8;
  public static final int RINGRESAR = 30;
  public static final int ELSE = 50;
  public static final int PTCOMA = 2;
  public static final int STRING = 42;
  public static final int ROR = 25;
  public static final int RVERDADERO = 43;
  public static final int RMENOR = 20;
  public static final int PARDER = 4;
  public static final int RFIN = 29;
  public static final int CORIZQ = 5;
  public static final int RIF = 49;
  public static final int DOLAR = 9;
  public static final int RCOMO = 31;
  public static final int RNOT = 27;
  public static final int RAND = 26;
  public static final int DOSPTS = 12;
  public static final int RMAYOR = 19;
  public static final int MAS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "CORIZQ",
  "CORDER",
  "LLAVIZQ",
  "LLAVDER",
  "DOLAR",
  "COMSIMPLE",
  "COMA",
  "DOSPTS",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "RPOTENCIA",
  "RMOD",
  "RMAYOR",
  "RMENOR",
  "RMAYORIGUAL",
  "RMENORIGUAL",
  "RIGUAL",
  "RDIFERENTE",
  "ROR",
  "RAND",
  "RNOT",
  "RINICIO",
  "RFIN",
  "RINGRESAR",
  "RCOMO",
  "RCONVALOR",
  "NOMVARIABLE",
  "NUMDATO",
  "FLOATDATO",
  "CADDATO",
  "BOOLDATO",
  "CARDATO",
  "FLECHAASIGN",
  "ENTERO",
  "CHAR",
  "STRING",
  "RVERDADERO",
  "RFALSO",
  "DECIMAL",
  "IGUAL",
  "UMENOS",
  "REVALUAR",
  "RIF",
  "ELSE",
  "RMIENTRAS",
  "RSI",
  "RENTONCES",
  "RFIN_SI",
  "RELSE",
  "ROSI"
  };
}

